---
title       : Interviewing Skills for Success: Walking into your Future Employer's Shoes 
subtitle    : 
author      : Ricardo Pietrobon, MBA
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hi theme     : tomorrow      #
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : self-contained # {standalone, draft}
---

<!-- has to use shoes combined with merrienboer -->
<!-- copied from http://career-advice.monster.com/job-interview/interview-preparation/boost-your-interview-iq/article.aspx 
-->


<!-- 
setwd("/Users/rpietro/articles/enactment")
library(slidify)
slidify("enactment_interviewing_skills.Rmd")
 -->

## Practice Good Nonverbal Communication 

* It's about demonstrating confidence: standing straight, making eye contact and connecting with a firm handshake. 
* That first nonverbal impression can be a great beginning -- or quick ending -- to your interview. 

---

## Dress for the Job or Company 

* Today's casual dress codes do not give you permission to dress as "they" do when you interview. 
* It is important to know what to wear to an interview and to be well-groomed. 
* Whether you wear a suit or something less formal depends on the company culture and the position you are seeking. 
* If possible, call to find out about the company dress code before the interview. 

---

## Listen 

* From the very beginning of the interview, your interviewer is giving you information, either directly or indirectly. 
* If you are not hearing it, you are missing a major opportunity. 
* Good communication skills include listening and letting the person know you heard what was said. 
* Observe your interviewer, and match that style and pace. 

---

## Don't Talk Too Much 

* Telling the interviewer more than he needs to know could be a fatal mistake. 
* When you have not prepared ahead of time, you may ramble when answering interview questions, sometimes talking yourself right out of the job. 
* Prepare for the interview by reading through the job posting, matching your skills with the position's requirements and relating only that information. 

---

## Don't Be Too Familiar 

* The interview is a professional meeting to talk business. 
* This is not about making a new friend. 
* Your level of familiarity should mimic the interviewer's demeanor. 
* It is important to bring energy and enthusiasm to the interview and to ask questions, but do not overstep your place as a candidate looking for a job. 

---

## Use Appropriate Language 

* It's a given that you should use professional language during the interview. 
* Be aware of any inappropriate slang words or references to age, race, religion, politics or sexual orientation -- these topics could send you out the door very quickly. 

---

## Don't Be Cocky 

* Attitude plays a key role in your interview success. 
* There is a fine balance between confidence, professionalism and modesty. 
* Even if you're putting on a performance to demonstrate your ability, overconfidence is as bad, if not worse, as being too reserved. 

---

## Take Care to Answer the Questions 

* When interviewers ask for an example of a time when you did something, they are asking behavioral interview questions, which are designed to elicit a sample of your past behavior. 
* If you fail to relate a specific example, you not only don't answer the question, but you also miss an opportunity to prove your ability and talk about your skills. 

---

## Ask Questions 

* When asked if they have any questions, most candidates answer, "No." Wrong answer. 
* Part of knowing how to interview is being ready to ask questions that demonstrate an interest in what goes on in the company. 
* Asking questions also gives you the opportunity to find out if this is the right place for you. 
* The best questions come from listening to what you're asked during the interview and asking for additional information. 

---

## Don't Appear Desperate 

* When you interview with the "please, please hire me" approach, you appear desperate and less confident. Reflect the three Cs during the interview: cool, calm and confidence. 
* You know you can do the job; make sure the interviewer believes you can, too.


<!-- 
exercise 1: funny t shirt, ask about what the company does

 -->